updated seller registration and user settings
map-of-pi/map-of-pi-backend-react pull request #136
Opened 2024-09-16 14:40 UTC by adisa39

updated seller and user preference services to save user coordinate during seller registration and user settings respectively

2024-09-17 16:28 UTC, DarinHajou approved these changes
LGTM!

2024-09-19 04:21 UTC, swoocn commented on src/services/seller.service.ts
> +    const sellCenter = await getMapCenterById(authUser.pi_uid);
Does this work for you @adisa39?  Were you able to test this..?  Asking because the mapCenterSchema consists of ->
 ```
 {
    map_center_id: { 
      type: String, 
      required: true, 
      unique: true 
    },
    search_map_center: {
      type: {
        type: String,
        enum: ['Point'],
        default: 'Point',
      },
      coordinates: {
        type: [Number],
        index: '2dsphere',
      },
    },
    sell_map_center: {
      type: {
        type: String,
        enum: ['Point'],
        default: 'Point',
      },
      coordinates: {
        type: [Number],
        index: '2dsphere',
      },
    },
  }
```
Appears to be some inconsistency with the data.
Did you update your branch with the latest from @DarinHajou's changes from [https://github.com/map-of-pi/map-of-pi-backend-react/pull/130 ](https://github.com/map-of-pi/map-of-pi-backend-react/pull/130 )?

2024-09-19 04:27 UTC, swoocn commented
This branch is outdated and needs to be synced with the latest dev.  Please address accordingly @adisa39.  Thanks!

2024-09-19 04:29 UTC, swoocn requested changes
Please review aforementioned comments.  If you want me to retrofit your changes to the current dev branch then let me know and I will be happy to do it.

2024-09-20 14:42 UTC, swoocn commented on src/services/seller.service.ts
> +    const sellCenter = await getMapCenterById(authUser.pi_uid);
Nevermind.

2024-09-20 14:42 UTC, swoocn commented
> Please review aforementioned comments. If you want me to retrofit your changes to the current dev branch then let me know and I will be happy to do it.

Nevermind.

2024-09-20 14:43 UTC, swoocn commented
> This branch is outdated and needs to be synced with the latest dev. Please address accordingly @adisa39. Thanks!

Nevermind.

2024-09-20 14:44 UTC, swoocn commented
Hi @adisa39! 
Just a quick update— Darin and I had a conversation this morning, and he will be removing the mapCenterSchema and instead rely on the search_map_center and sell_map_center properties in the userSettingsSchema and sellerSchema, respectively.  Once those changes are merged, I'll revisit this PR accordingly.  Sorry for the confusion and thanks for your patience!

2024-09-21 19:56 UTC, merged